"use client";
const sections = [
  {
    title: "INTRODUCTION",
    content: [
      "Welcome to SAJA, your trusted platform for survey creation and data analytics. In the context of this Privacy Policy:",
      "‘Client’ refers to individuals or organizations that create and manage surveys using SAJA's services.",
      "‘Responder’ refers to individuals who participate in surveys created by clients using SAJA's platform.",
      "At SAJA, we prioritize the privacy and security of your data. This Privacy Policy is designed to provide you with a clear understanding of how we collect, use, and protect your information. By using SAJA's services, you agree to the terms outlined in this policy.",
      "Our commitment to your privacy is unwavering, and we have implemented stringent measures to ensure the confidentiality and security of your data. Please take a moment to review this policy to better understand how we handle your information.",
      "If you have any questions or concerns regarding our Privacy Policy, please do not hesitate to contact us. Your privacy and trust in SAJA are of utmost importance to us.",
    ],
  },
  {
    title: "INFORMATION WE COLLECT",
    content: [
      "For Clients",
      "When you register with SAJA, we may collect your registration information, including your name, email address, and contact details. This information is used for account creation, communication, and support purposes.",
      "For Responders",
      "Responders should be aware that surveys created and shared via SAJA are neither created nor endorsed by SAJA.",
      "While survey response data is transmitted to SAJA's servers, SAJA does not access or use this data. Only clients have access to the data collected from their surveys.",
      "Registration, Billing, and Account Information (For Clients)",
      "Clients may be required to provide billing information, such as billing address and payment details, for subscription purposes. This information is securely processed by our payment service provider, and SAJA does not store sensitive billing information.",
      "Your account information, including login credentials and account settings, is protected with strong encryption and is accessible only to you. SAJA does not access or share your account information without your explicit consent.",
      "Client Data Collection (Net Promoter Score)",
      "SAJA collects Net Promoter Score (NPS) data sector-wise to provide benchmark scores for our clients. These benchmark scores are used to measure the performance of your business within your industry.",
      "To provide context, the benchmark score represents the average NPS score for businesses in the same sector. This benchmark allows our clients to assess whether their NPS score falls within the expected range for their industry.",
      "It's important to note that individual client scores are not identifiable within the benchmark score, as this score is compiled from multiple businesses in the same sector. The benchmark score is automatically generated by our system to help clients gauge their performance within their industry.",
      "Client Anonymity",
      "SAJA respects the privacy of clients and maintains their anonymity. Client data is not disclosed or shared without consent.",
      "We are committed to ensuring your data privacy and security. If you have any questions or concerns about the information we collect or how it is used, please contact us. Your trust in SAJA is our highest priority.",
    ],
  },
  {
    title: "PURPOSE OF COLLECTION",
    content: [
      "At SAJA, we collect data for specific, well-defined purposes that enhance your experience as a client and safeguard the privacy of responders. Here are the primary purposes for which we collect data:",
      "For Clients",
      "Account Management: The registration information we collect allows us to create and maintain your account. It enables us to provide you with access to our services, manage your subscriptions, and facilitate communication with you.",
      "Billing: If you subscribe to our premium services, we collect billing information to process payments securely. SAJA does not store sensitive billing details. This information is used solely for billing purposes.",
      "Service Improvement: Data collected sector/industry-wise, including Net Promoter Scores, is used to gain insights and improve our services. This helps us tailor our offerings to better suit your needs and expectations.",
      "Client Anonymity: We ensure the anonymity of our clients. Your identity and data are protected. We do not disclose or share your information without your explicit consent.",
      "For Responders",
      "Survey Participation: Responders should be aware that surveys shared on SAJA are created by clients and are not endorsed by SAJA. The purpose of collecting your responses is determined by the client. It is essential to review the respective client's privacy policy for details on how your data will be used.",
      "Data Privacy: SAJA collects survey response data for transmission to clients' accounts. SAJA does not access or use this data. Clients are the only ones with access to the data collected from their surveys.",
      "Security and Privacy: Responders are advised not to share sensitive or personal information within surveys unless they trust the source explicitly. Protecting your data and privacy is essential to us.",
      "Our commitment to data privacy is unwavering. The data collected is used exclusively for the purposes outlined above. We respect your privacy and take measures to ensure the security of your information. If you have any questions about how your data is used or concerns about its privacy, please don't hesitate to reach out to us.",
    ],
  },
  {
    title: "DATA SHARING",
    content: [
      "Client Data Sharing:",
      "SAJA does not share client data, including registration and billing information, with third parties. Your information is held in strict confidence and is not disclosed to external entities unless required by applicable law or with your explicit consent.",
      "The Net Promoter Score (NPS) data collected sector/industry-wise is used solely for improving our services and enhancing your experience. It is not shared with third parties in a way that identifies individual clients.",
      "Responder Data Sharing:",
      "SAJA emphasizes that survey data collected from responders is shared exclusively with the clients who created and own the respective surveys. SAJA does not access or use this data for any purpose.",
      "Responders are responsible for reviewing the privacy policies of clients and understanding how their data will be used within specific surveys.",
      "Exceptions:",
      "The only exception to data sharing is when a client explicitly reaches out to SAJA to form a partnership for data analytics. In such cases, data-sharing agreements are established separately and in compliance with applicable data protection laws and regulations.",
      "At SAJA, we prioritize the privacy and security of your data. We do not engage in the unauthorized sharing or disclosure of your information. Your trust in our commitment to data privacy is our utmost priority.",
    ],
  },
  {
    title: "DATA SECURITY",
    content: [
      "At SAJA, we take data security seriously and have implemented robust measures to protect your information:",
      "Secure Server: We employ a secure server with Strong SHA-2 & 2048-bit encryption to safeguard the data you entrust to us. This advanced encryption ensures that your data remains confidential and tamper-resistant during transmission.",
      "Dedicated Server: SAJA maintains a dedicated server to host your data. This dedicated infrastructure is designed to enhance the security and availability of your information.",
      "Dedicated Team: Our dedicated team of professionals is committed to maintaining the security of our systems and your data. They regularly monitor for potential threats and take prompt action to address any security concerns.",
      "Link Encryption: We utilize link encryption to protect data during transmission between your devices and our servers. This additional layer of security ensures that your data remains protected as it travels over the internet.",
      "Data Encryption: Rest assured, your data is safe with us. We implement data encryption protocols to safeguard your information, whether it's stored on our servers or transmitted between devices.",
      "SAJA prioritizes the security and confidentiality of your data. Our commitment to using state-of-the-art security measures ensures that your information is protected against unauthorized access, tampering, or data breaches. Your trust in our data security practices is fundamental to our service.",
    ],
  },
  {
    title: "DATA RIGHTS",
    content: [
      "Under the EU's General Data Protection Regulation (GDPR), you have the following rights with respect to your personal data:",
      "Right of Access: You have the right to request access to the personal data we hold about you and information related to how we process it.",
      "Right to Rectification: You have the right to request that any inaccurate or incomplete personal data we hold about you be corrected.",
      "Right to Erasure: You have the right to request the deletion of your personal data in certain circumstances, such as when it is no longer necessary for the purposes for which it was collected.",
      "Right to Restrict Processing: You have the right to request that we restrict the processing of your personal data in certain cases, such as if you believe the data is inaccurate.",
      "Right to Object: You have the right to object to the processing of your personal data for direct marketing purposes or for reasons relating to your particular situation.",
      "Right to Data Portability: You have the right to request a copy of your personal data in a machine-readable format. You can also request that we transmit this data directly to another controller.",
      "Right to Withdraw Consent: If processing is based on consent, you have the right to withdraw your consent at any time.",
      "To exercise any of these rights, please contact us using the contact details provided in this privacy policy. We will respond to your request in accordance with applicable data protection laws.",
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-linear-to-br from-slate-50 via-white to-gray-100">
      <div className="max-w-6xl mx-auto px-4 md:px-8 pb-16">
        {/* Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center px-4 py-2 rounded-full bg-[#0095DA] text-white text-sm font-medium mb-6">
            Privacy & Security
          </div>

          <h1 className="text-4xl md:text-6xl font-black  mb-6 tracking-tight">
            Privacy Policy
          </h1>

          <p className="text-gray-600 text-lg max-w-3xl mx-auto leading-relaxed">
            Your privacy and trust in SAJA are of utmost importance to us.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-10">
          {sections.map((section, index) => (
            <div
              key={index}
              className="bg-white/80   rounded-3xl overflow-hidden"
            >
              {/* Section Header */}
              <div className="border-b border-gray-100  px-6 md:px-10 py-2">
                <h2 className="text-2xl md:text-3xl font-bold ">
                  {section.title}
                </h2>
              </div>

              {/* Section Content */}
              <div className="px-6 md:px-10 py-8 space-y-5">
                {section.content.map((text, i) => {
                  const isHeading =
                    text === "For Clients" ||
                    text === "For Responders" ||
                    text === "Client Data Sharing:" ||
                    text === "Responder Data Sharing:" ||
                    text === "Exceptions:" ||
                    text === "Client Anonymity" ||
                    text === "Client Data Collection (Net Promoter Score)" ||
                    text ===
                      "Registration, Billing, and Account Information (For Clients)";

                  return (
                    <div key={i}>
                      {isHeading ? (
                        <h3 className="text-xl font-bold text-gray-900 mt-8 mb-3">
                          {text}
                        </h3>
                      ) : (
                        <p className="text-gray-700 leading-8 text-[15px] md:text-base">
                          {text}
                        </p>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-16 bg-[#0095DA] rounded-3xl p-8 md:p-12 text-white">
          <div className="grid md:grid-cols-2 gap-8">
            <div>
              <h3 className="text-2xl font-bold mb-4">Contact Us</h3>

              <div className="space-y-3 text-gray-300">
                <p>Email: hello@saja.biz</p>
                <p>Address: Saja, Douglas, Isle of Man</p>
              </div>
            </div>

            <div>
              <h3 className="text-2xl font-bold mb-4">
                Acceptance of Privacy Policy
              </h3>

              <p className="text-gray-300 leading-7">
                By using SAJA's services, you signify your acceptance of this
                Privacy Policy. If you do not agree to this policy, please do
                not use our services.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}